expectThrows<Exception>(void Function() f) {}

main() {}

test(dynamic x, dynamic list) {}
